import { createClient } from "@/lib/supabase/server"

type Row=Record<string,unknown>
const norm=(v:string)=>v.toLowerCase().replace(/[\s_-]+/g,"")
const text=(v:unknown)=>v==null?"":String(v).trim()
const num=(v:unknown)=>{const n=Number(text(v).replace(/[₹$€£,%\s]/g,""));return Number.isFinite(n)?n:0}
const date=(v:unknown)=>{const s=text(v); if(!s)return null; const m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/); return m?`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`:null}
function key(row:Row, aliases:string[]){const m=new Map(Object.keys(row).map(k=>[norm(k),k]));for(const a of aliases){const k=m.get(norm(a));if(k)return k}return null}
export type InvestigateData={businessName:string;currencyCode:string;latestDate:string|null;rows:Row[];columns:string[];summary:{revenue:number;orders:number;units:number;customers:number}}
export async function getInvestigateData():Promise<InvestigateData>{const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const {data:m,error:me}=await s.from("business_users").select("business_id").eq("user_id",user.id).limit(1).maybeSingle();if(me)throw new Error(me.message);if(!m)throw new Error("BUSINESS_REQUIRED");const [{data:b,error:be},{data:ds,error:de}]=await Promise.all([s.from("businesses").select("name,currency_code").eq("id",m.business_id).single(),s.from("datasets").select("id,name,file_name,row_count,status,created_at").eq("business_id",m.business_id).eq("status","ready").order("created_at",{ascending:false}).limit(50)]);if(be||!b)throw new Error(be?.message||"Business could not be loaded.");if(de)throw new Error(de.message);const ids=(ds??[]).map((d:{id:string})=>d.id);const {data:stored,error:re}=ids.length?await s.from("dataset_rows").select("row_data").eq("business_id",m.business_id).in("dataset_id",ids).order("row_number",{ascending:true}):{data:[],error:null};if(re)throw new Error(re.message);const rows=((stored??[]) as Array<{row_data:unknown}>).map(x=>(x.row_data??{}) as Row);const first=rows[0]??{};const revenue=key(first,["revenue","sales","amount","total"]),order=key(first,["order_id","orderid","order"]),units=key(first,["quantity","qty","units"]),customer=key(first,["customer_id","customer","customer_name","client"]),dt=key(first,["order_date","transaction_date","date","created_at"]);const latest=rows.map(r=>dt?date(r[dt]):null).filter(Boolean).sort().at(-1)??null;const customers=new Set(rows.map(r=>customer?text(r[customer]):"").filter(Boolean));return {businessName:b.name,currencyCode:b.currency_code||"INR",latestDate:latest,rows,columns:Object.keys(first),summary:{revenue:rows.reduce((a,r)=>a+(revenue?num(r[revenue]):0),0),orders:order?new Set(rows.map(r=>text(r[order]))).size:rows.length,units:rows.reduce((a,r)=>a+(units?num(r[units]):0),0),customers:customers.size}}}
