"use client"

import { useMemo, useState } from "react"
import { Search, SlidersHorizontal, ArrowUpRight, Package, Truck, FolderKanban, History, Users, Activity } from "lucide-react"

type Row=Record<string,unknown>
const text=(v:unknown)=>v==null?"":String(v)
const num=(v:unknown)=>{const n=Number(text(v).replace(/[₹$€£,%\s]/g,""));return Number.isFinite(n)?n:0}
const norm=(v:string)=>v.toLowerCase().replace(/[\s_-]+/g,"")
function find(row:Row, aliases:string[]){const m=new Map(Object.keys(row).map(k=>[norm(k),k]));for(const a of aliases){const k=m.get(norm(a));if(k)return k}return null}

type Kind="autopsy"|"entities"|"inventory"|"suppliers"|"projects"|"changes"
type Config={eyebrow:string;title:string;description:string;aliases:string[];primary:string[];secondary:string[];icon:React.ElementType;metric:string;empty:string}
const configs:Record<Kind,Config>={
 autopsy:{eyebrow:"Business autopsy",title:"Find the stories hiding in the numbers.",description:"Trace important business signals back to the records that produced them.",aliases:["revenue","sales","amount","total"],primary:["revenue","sales","amount","total"],secondary:["date","order_date","transaction_date"],icon:Activity,metric:"Financial value",empty:"No records are available for the autopsy yet."},
 entities:{eyebrow:"Entity explorer",title:"Explore the people and things behind performance.",description:"Move from a connected record to the customers, products, and entities represented inside it.",aliases:["customer","customer_name","customer_id","product","product_id"],primary:["customer","customer_name","customer_id"],secondary:["product","product_name","product_id"],icon:Users,metric:"Entity matches",empty:"No customer or product identifiers were found."},
 inventory:{eyebrow:"Inventory investigation",title:"Know what is sitting on the shelf.",description:"Investigate stock quantities, product movement, and records that may need replenishment attention.",aliases:["quantity","qty","units","stock","inventory"],primary:["quantity","qty","units","stock","inventory"],secondary:["product","product_name","sku"],icon:Package,metric:"Units / stock",empty:"No inventory-oriented fields were detected."},
 suppliers:{eyebrow:"Supplier investigation",title:"Trace supply risk to its source.",description:"Search supplier and vendor records to understand dependency, activity, and operational exposure.",aliases:["supplier","supplier_name","vendor","vendor_name"],primary:["supplier","supplier_name","vendor","vendor_name"],secondary:["product","product_name","sku"],icon:Truck,metric:"Supplier activity",empty:"No supplier or vendor identifiers were found."},
 projects:{eyebrow:"Project investigation",title:"Keep operational work visible.",description:"Inspect project, owner, status, and delivery records without losing the underlying evidence.",aliases:["project","project_name","owner","status"],primary:["project","project_name"],secondary:["owner","status","stage"],icon:FolderKanban,metric:"Project records",empty:"No project-oriented fields were detected."},
 changes:{eyebrow:"Change investigation",title:"See what moved and when.",description:"Use dates and update fields to investigate recent movement across the connected business data.",aliases:["date","order_date","transaction_date","updated_at"],primary:["date","order_date","transaction_date","updated_at"],secondary:["status","updated_at","created_at"],icon:History,metric:"Date matches",empty:"No date fields were detected in the connected records."},
}

export default function InvestigateOverview({kind,rows,columns,currencyCode}:{kind:Kind;rows:Row[];columns:string[];currencyCode:string}){
 const cfg=configs[kind], [query,setQuery]=useState(""),[visible,setVisible]=useState(50)
 const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return q?rows.filter(r=>Object.values(r).some(v=>text(v).toLowerCase().includes(q))):rows},[rows,query])
 const first=rows[0]??{}, primary=find(first,cfg.primary), secondary=find(first,cfg.secondary)
 const primaryTotal=filtered.reduce((s,r)=>s+(primary?num(r[primary]):0),0)
 const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:currencyCode||"INR",maximumFractionDigits:0})
 const Icon=cfg.icon
 const focusLabel=primary?primary:cfg.metric
 return <div className="min-h-full bg-[#F1F0F8] px-5 py-8 lg:px-10 lg:py-10"><div className="mx-auto max-w-[1300px]">
  <header className="mb-7"><div className="flex items-start gap-4"><div className="mt-1 flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#17153B] text-white"><Icon className="h-5 w-5"/></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[#433D8B]">{cfg.eyebrow}</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.045em] text-[#17153B]">{cfg.title}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#68647A]">{cfg.description}</p></div></div></header>
  <div className="grid gap-4 md:grid-cols-3"><Metric label="Records" value={filtered.length.toLocaleString("en-IN")} detail={query?"Matching search":"Connected records"}/><Metric label={focusLabel} value={primary?money.format(primaryTotal):columns.length.toString()} detail={primary?`Calculated across matching records`:`${columns.length} connected fields`}/><Metric label={secondary?secondary:"Investigation focus"} value={secondary?new Set(filtered.map(r=>text(r[secondary])).filter(Boolean)).size.toLocaleString("en-IN"):kind} detail={secondary?"Distinct values":"Domain-specific view"}/></div>
  <section className="mt-5 overflow-hidden rounded-3xl border border-[#E7E4EF] bg-white"><div className="flex flex-col gap-3 border-b border-[#E7E4EF] p-5 md:flex-row md:items-center md:justify-between"><div className="relative max-w-xl flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9A94A8]"/><input value={query} onChange={e=>{setQuery(e.target.value);setVisible(50)}} placeholder={`Search ${cfg.eyebrow.toLowerCase()}...`} className="w-full rounded-xl border border-[#E7E4EF] bg-[#FAF9FC] py-2.5 pl-9 pr-3 text-sm text-[#17153B] outline-none focus:border-[#433D8B]"/></div><div className="flex items-center gap-2 text-xs text-[#68647A]"><SlidersHorizontal className="h-4 w-4"/> {columns.length} fields · {kind}</div></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr className="border-b border-[#E7E4EF] text-left text-[9px] uppercase tracking-[0.14em] text-[#9A94A8]">{columns.slice(0,8).map(c=><th key={c} className="px-4 py-3">{c}</th>)}<th className="px-4 py-3">Inspect</th></tr></thead><tbody className="divide-y divide-[#E7E4EF]">{filtered.slice(0,visible).map((row,i)=><tr key={i} className="text-xs hover:bg-[#FAF9FC]">{columns.slice(0,8).map(c=><td key={c} className="max-w-[220px] truncate px-4 py-3.5 text-[#4F4A62]">{text(row[c])||"—"}</td>)}<td className="px-4 py-3.5"><button type="button" className="inline-flex items-center gap-1 text-[#433D8B]">Open <ArrowUpRight className="h-3.5 w-3.5"/></button></td></tr>)}</tbody></table>{filtered.length===0&&<div className="p-12 text-center"><Icon className="mx-auto h-7 w-7 text-[#9A94A8]"/><p className="mt-3 text-sm text-[#68647A]">{query?"No connected records match this search.":cfg.empty}</p></div>}</div>{visible<filtered.length&&<div className="border-t border-[#E7E4EF] p-4 text-center"><button type="button" onClick={()=>setVisible(v=>v+50)} className="text-xs font-medium text-[#433D8B]">Load 50 more</button></div>}</section>
 </div></div>
}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className="rounded-2xl border border-[#E7E4EF] bg-white p-5"><p className="text-[10px] uppercase tracking-[0.15em] text-[#9A94A8]">{label}</p><p className="mt-3 truncate text-2xl font-semibold text-[#17153B]">{value}</p><p className="mt-1 text-xs text-[#9A94A8]">{detail}</p></div>}
